name: Validate

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - name: HASS validation
        uses: "home-assistant/actions/hassfest@master"

      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: integration
    